#!/bin/sh
# Copyright (C) 2014 Russell Haley
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

help="\
dirstruct - mirror a directory structure

	Replicates the top-level directory structure of <source dir> 
	in the current directory.

usage: 
	dirstruct <source dir>
"

if [ -d "$1" ]
then
	find "$1" -mindepth 1 -maxdepth 1 -type d -printf '%f\0' | xargs -0 mkdir
else
	echo "$help"
fi

