#!/bin/sh

help="\
dirstruct - mirror a directory structure

	Replicates the top-level directory structure of <source dir> 
	in the current directory.

usage: 
	dirstruct <source dir>
"

#find "$1" -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 -I xxx echo "mkdir \"\`basename \"xxx\"\`\"" | sh

if [ -d "$1" ]
then
	find "$1" -mindepth 1 -maxdepth 1 -type d -printf '%f\0' | xargs -0 mkdir
else
	echo "$help"
fi

