#!/bin/bash
# Copyright (C) 2014 Russell Haley
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

help="\
git-multi: run git commands in multiple repositories

Usage:
	git-multi <action> <repository-directory...>
"

iwd="$(pwd)"

if [ $# -lt 2 ]; then
	echo "$help"
	exit 1
fi

action="$1"
shift

for repo in "$@"; do
	cd "$repo"
	printf "\ngit $action in $repo\n"
	git $action
	cd "$iwd"
done


